server.port: 7001
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

spring.cloud.function.definition: messageProcessor

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.messageProcessor-in-0:
    destination: products
    group: productsGroup


logging:
  level:
    root: INFO
    se.aw: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring:
  config:
    activate:
      on-profile: docker

spring.data.mongodb.host: mongodb

server.port: 8080
